### ISSUE TITLE
NaPl Lieu

### ISSUE THREAD

**Issue by valamercery** [Semantic-Data-for-Humanities/Alignement_symogih.org#30]
### Résumé
**Scope note**
Selon la définition classique propre aux gazetteers, un lieu, « named-place », est défini et identifié par : un nom, un type et une localisation géographique (ponctuelle ou surfacique). C'est une portion d’espace géographique que l’on peut localiser, nommer et définir.

Dans le modèle du projet symogih.org, l'entité Lieu (Named Place) prend en compte les lieux que l’on peut se représenter comme une surface indépendamment de tout type de construction.  Il peut s’agir d’éléments géographiques naturels (forêt, fleuve, montagne…) ou artificiels, si on les imagine comme une surface couvrante, délimitée par une frontière plus ou moins précise (voie de circulation, adresse, désignation de pays ou lieu habité, découpage du cadastre…).

**Lien**
https://ontome.net/class/309

**Hiérarchie**
subClassOf [sym:LoOb Objet localisé](https://ontome.net/class/307)

#### Alignement proposé
owl:equivalentClass [sdh:C13 Geographical Place](https://ontome.net/class/363)
#### Alignement des relations
| Relation | Alignement | Note |
|--|--|--|
|Nom||Voir #161 |
|Localisation||Voir #164 et #188 |
|Année de début||Voir #178  |
|Année de fin||Voir #178  |
|Notes ||Voir #180 |
|Propriété texte||Voir #167 |
|Classes||Voir #175 |
|Associations de lieux||Voir #181 |
|Associations des formes concrètes||Voir #182 |
|Documentation||Voir #183  |
|Lien vers ressource web (URI)||Voir #162 |
|Commentaires||Voir #173 |
|Association à un projet | |Voir #176 |
|Annotations||Voir #177 |

### Commentaires
Les types de lieux étant de vrais "types", il serait préférable de les considérer ainsi et d'utiliser un seul alignement pour tous ces objets en les typant :

* sdh:C13 Geographical Place _sdh:P20 has geographical place type_ sdh:C14 Geographical Place Type
* Voir aussi les ce ticket geovistory/toolbox#273 sur le typage des Geographical Place.

| Type | Id AbOb | Nombre d'instances de NaPl |
| ----- | ------------ | -------------------------------------- |
| [Lieu habité](https://ontome.net/class/305) |	156	| 49644 |
| [Région géographique](https://ontome.net/class/293) |	245	| 84 |
| [Adresse](https://ontome.net/class/266) |	695	| 30587 |
| [Élément géographique naturel](https://ontome.net/class/310) |	696	| 576 |
| [Territoire](https://ontome.net/class/326) |	697	| 46371 |
| [Surface d'infrastructure](https://ontome.net/class/304) |	698	| 202 |

**Comment by stephenhart8** [comment]
Quelle distinction existe-t-il entre une "région géographique" et un "territoire"? Si cette distinction n'est que purement administrative, cela ne devrait-il par être modélisé dans la sphère sociale?
Une adresse est-elle un Geographical Place? Ou devrait-on la concevoir comme un "contact point"? Quelle serait la différence entre une adresse et la surface d'infrastructure où réside une personne?

**Comment by stephenhart8** [comment]
En dehors des types associés, l'équivalence de classe ne me semble pas poser de problème.
Y a-t-il un équivalent à E53 Place dans Symogih?

**Comment by valamercery** [comment]
Dans symogih.org :

*   la distinction entre "région géographique" et "territoire" est avant tout légale, un territoire étant défini légalement, une région géographique étant définie par l'usage ou la pratique humaine.
*   une adresse est considérée comme l'identification d'un lieu localisé dans un espace urbain et donc un Geographical Place. La personne réside dans la construction qui se situe à cette adresse.
*   l'équivalent de E53 sont les #164

**Comment by valamercery** [comment]
L'alignement de la classe NaPl est validé. Avant de pouvoir importer les données, il est proposé de créer les kinds correspondants aux types de NaPl.

crm:E55 -> sdh:Kind -> sdh:Geographical Place Kind (tâche confiée @stephenhart8 )

[FB, 25 avril 2023] :
- pour la propriété identifiante (qui associe le kind) utiliser l'actuelle [sdh:P20 has identifying geographical place type](https://ontome.net/property/1110/namespace/3)
- les types actuels ( sdh:C14 Geographical Place Type) seront associés via la classification (sdh:C48 Geographical Place Classification)
- pour tout statement actuel sdh:P20 on va produire une instance de sdh:C48 GP Classification
- on aligne les types actuels avec les kinds
- on remplace ensuite dans le modèle et profil la classe sdh:C14 par sdh:C51 Geographical Place Kind
- dans les données on met dans le target de chaque statement sdh:P20 l'instance de kind qui correspond à l'actuel type

**Comment by stephenhart8** [comment]
Because statements need to be preserved in the Geovistory model, it is important that the shift from [sdh:P20 has identifying geographical place type](https://ontome.net/property/1110/namespace/3) to Geographical Place Kind is done in different steps:

1. Creation of the classes Kind et Geographical Place Kind (done)
2. Duplication of the information linked to [sdh:P20 has identifying geographical place type](https://ontome.net/property/1110/namespace/3) to [P63 classifies (is classified by)](https://ontome.net/property/2124/namespace/3), so that in information documented is preserved.
3. Creation of the Kind vocabulary, and creation of the [C51 Geographical Place Kind](https://ontome.net/class/1210/namespace/3) instances
4. Creation of a corresponding table between the vocabulary terms used by the different projects to the Kinds created in the step 3
5. Modify the property [sdh:P20 has identifying geographical place type](https://ontome.net/property/1110/namespace/3) in OntoMe so that it's linked to the instances of [C51 Geographical Place Kind](https://ontome.net/class/1210/namespace/3). 

This should allow the preservation of the statements.

**Comment by stephenhart8** [comment]
L'approche proposée le 25 avril est acceptée, avec pour différent kinds:

- Lieu habité
- Région géographique (à appeler "zone géographique"?)
- Adresse
- Élément géographique naturel
- Territoire
- Surface d'infrastructure (avec la scope note à réduire)

**Comment by stephenhart8** [comment]
### Region - Région

###### Définition FR

Lieu géographique dont l'unité est définie par des caractères physiques ou par les résultats de l'activité humaine (économie, système de production). il est ici conçue en termes génériques et peut être naturel, historique, économique, etc. En d'autres termes, il résulte d'un découpage particulier de l'espace en fonction des critères retenus par le chercheur.

[[REGION : Définition de REGION](http://www.cnrtl.fr/definition/region)](http://www.cnrtl.fr/definition/region)

##### Définition EN

Geographical place whose unity is defined by physical features or by the results of human activity (economy, production system). It is conceived here in generic terms: it may be natural, historical, economic, etc. In other words, it is the result of a particular division of space according to the criteria chosen by the researcher.

###### Exemples

- Le bassin minier du nord de la France
  
- Le pourtour méditerranéen
  
- La Scandinavie
  
- La région genevoise, qui peut inclure les région limitrophes, notamment en France (contrairement au territoire du canton de Genève)
  
- Le bassin lémanique
  

###### Cas limites

- Camargue: S'agit-il ici d'une Région, ou d'un Élément naturel? La distinction entre une région naturel et un élément naturel peut parfois être floue.
  

### Legal Territory - Territoire légal (juridique?)

##### Définition FR

Lieu géographique comprenant des territoires de surface terrestre, plus ou moins clairement définis par le droit ou l'usage, qui ont généralement une certaine unité, un caractère particulier avec une communauté humaine établie. Il comprend toutes les surfaces territoriales administratives, juridiques, ecclésiastiques, etc. définies par des frontières plus ou moins précises tracées par l'être humain et relevant d'une autorité.

##### Définition EN

Geographical place that comprises territories of the land surface, more or less clearly defined by law or custom, which generally have a certain unity, a special character with an established human community. It includes all administrative-territorial surfaces, legal, ecclesiastical, etc. defined by more or less precise borders drawn by human beings and the subject of an authority.

##### Exemples

- France (pays)
  
- Diocèse de Bâle
  
- Parcelle cadastrale 868 du canton de Bern (Unitobler de l'UNIBE)
  

###### Cas limites

- Le quartier de Montmartre, qui doit plutôt être documenté comme un une *Zone, plutôt que comme un Territoire: Montmartre n'a aujourd'hui aucune limite géographique précise : c'est un quartier parisien « historique » et non un « quartier administratif ». cf. [[Montmartre — Wikipédia](https://fr.wikipedia.org/wiki/Montmartre)](https://fr.wikipedia.org/wiki/Montmartre)
  

### Settlement - Lieu habité

##### Définition FR

Lieu géographique comprenant une portion de la surface terrestre dont la caractéristique est d'être le lieu d'occupation d'une ou plusieurs communautés de populations humaines, de manière permanente ou périodique. Un lieu habité possède une certaine unité, tant physique (l'étendue des surfaces d'habitation) que culturelle (possédant un caractère particulier pour une ou plusieurs communautés humaines établies).

##### Definition EN

Geographical Place that comprises a portion of the land surface, the characteristic of which is that it is occupied by one or more communities of human populations, either permanently or periodically. A settlement has a certain unity, both physical (the extent of the inhabited areas) and cultural (having a particular character for one or more established human communities).

###### Exemples

- La ville de Genève (en opposition au territoire du canton de Genève)
  
- Avarga, capitale hivernale mongole de Genghis Khan ([[Avarga - Wikipedia](https://en.wikipedia.org/wiki/Avarga)](https://en.wikipedia.org/wiki/Avarga))
  
- Campement paléolithique saisonnier d'Étiolles ([[Étiolles, Campements paléolithiques | Archéologie | culture.fr](https://archeologie.culture.gouv.fr/fr/etiolles-campements-paleolithiques)](https://archeologie.culture.gouv.fr/fr/etiolles-campements-paleolithiques))
  

###### Cas limites

- Le village de Montmartre avant de rejoindre Paris: Bien que possédant sa propre identité, le quartier de Montmatre fait actuellement partie de la ville de Paris (il est donc une partie du Geographical Place "Paris" ayant pour Kind "Lieu habité" et peut être documenté comme une *Zone). Avant son rattachement à la ville de Paris, Montmartre pourrait être documenté comme un Lieu habité.
  

### Address - Adresse

##### Définition FR

Lieu géographique comprenant des lieux nommés définis par une indication précise de leur emplacement. Au minimum, une adresse se compose d'un nom de lieu (par exemple le nom d'une rue) et d'une autre indication (par exemple un numéro). Il s'agit d'un point fixe dans l'espace qui ne comprend pas la surface du terrain de cette adresse, qui pourrait être documentée comme un Territoire légal pour une parcelle cadastrale, ou documentée comme la surface d'infrastructure pour la partie du terrain couverte par l'installation construite par l'homme qui se trouve à cette adresse.

##### Definition EN

Geographical Place that comprises named places defined by an accurate indication of their location. At least, an address consists of a place name (eg street name) and another indication (eg a number). It is a fixed point in space and does not comprise the land surface of that address, which could be documented as a Legal Territory for the cadastral plot, or documented as the Infrastructure Surface Area for the part of the land covered by the human-made installation that sits at this address.

###### Exemples

- Lerchenweg 32, 3012 Bern (adresse de l'Unitober de l'UNIBE)
- km 125 de l'A41N, sens Chambéry-Genève (aire de La Ripaille)

###### Cas limites

- ?
  

### Natural Element - Élément naturel

##### Définition FR

Lieu géographique dont l'unité est définie par des caractères physiques (constitution géologique, relief, climat, végétation, etc.) et dont le découpage est plus ou moins bien délimité et reposant sur des caractéristiques naturelles objectives et non sociales (bien qu'un tel découpage peut être interprété différemment selon les individus ou groupes sociaux, comme une unique montagne étant distinguées par certains chercheurs en deux entités différentes en raison de caractéristiques géologiques).

##### Definition EN

Geographical Place whose unity is defined by physical characteristics (geological constitution, relief, climate, vegetation, etc.) and whose division is more or less well defined and based on objective natural characteristics and not social characteristics (although such a division may be interpreted differently by different individuals or social groups, such as a single mountain being divided by some researchers into two different entities based on geological characteristics).

###### Exemples

- Mont Blanc
- Lac Léman
- Fleuve Amazone
- Corse (l'île)

###### Cas limites

- Camargue: S'agit-il ici d'une Région, ou d'un Élément naturel? La distinction entre une région naturel et un élément naturel peut parfois être floue.
  

###### Edge Cases

## Infrastructure (Construction?) Surface Area - Surface d'infrastructure

##### Definition FR

Lieu géographique comprenant les surfaces terrestres couvertes par des installations humaines qui déterminent le fonctionnement d'une organisation ou d'une entreprise, l'économie d'une région, d'un pays, etc. Ces surfaces d'infrastructures peuvent s'étendre au delà de la surface occupée par des bâtiments, comme la surface d'un aéroport qui comprendrait les terminaux, les rampes, les pistes, les hangars et d'autres installations. Les surfaces d'infrastructures doivent être distinguées des parcelles cadastrales où elles peuvent être situées, ces dernières étant documentées en tant que territoires légaux.

##### Définition EN

Geographical Place that comprises land surfaces covered by human-made installations that determine the functioning of an organization or business, the economy of a region, a country, etc. Such Infrastructures Surface Areas may extend beyond the actual surface area occupied by buildings, such as the surface area of an airport that would include the terminals, ramp, runway, hangars, and other facilities. Infrastructures Surface Areas should be distinguished from the cadastral plots where they may be situated, the latter being documented as Legal Territories.

###### Exemples

- Unitobler de l'UNIBE (la surface, en opposition au bâtiment lui-même ou à la parcelle cadastrale)
- L'A41N (la surface que l'autoroute occupe)

###### Edge Cases

### Section

##### Définition FR

Lieu géographique comprenant des parties d'autres formes de lieux géographiques, découpées selon les critères ne répondant pas aux exigences des autres formes de lieux géographiques. _À améliorer/compléter_

###### Exemples

- Le quartier de Montmartre: Montmartre n'a aujourd'hui aucune limite géographique précise : c'est un quartier parisien « historique » et non un « quartier administratif ». cf. [[Montmartre — Wikipédia](https://fr.wikipedia.org/wiki/Montmartre)](https://fr.wikipedia.org/wiki/Montmartre)

**Comment by stephenhart8** [comment]
Conformément à la discussion du 7 juin 2023, une page confluence a été créée pour discuter des définitions des Kinds: https://kleiolab.atlassian.net/wiki/spaces/DT/pages/3467149746/Definition+of+Kinds
À vos claviers pour les commentaires!
