### ISSUE TITLE
TyIn170 Destruction

### ISSUE THREAD

**Issue by MPica** [Semantic-Data-for-Humanities/Alignement_symogih.org#96]
### Résumé

**Scope note**

[WIP] Ce type d'information permet de renseigner la destruction d'un objet matériel. Cela correspond à la fin d'existence de l'objet : une fois détruit, l'objet n'existe plus en tant qu'objet matériel.	Ce type d'information est semblable à la classe E6 Destruction du CIDOC CRM. Dans le cas d'une destruction intentionnelle pratiquée par un acteur individuel ou collectif, ce type d'information est également une sous-classe de la classe E7 Activity.

**Lien**

[https://ontome.net/ns/symogih/TyIn170](https://ontome.net/ns/symogih/TyIn170)

**Aucune information Destruction n'a été créée dans la BHP**

### Alignement

**Alignement proposé** :

#### Alignement des rôles

| Rôle (tel qu'apparaissant dans OntoME) | Range | Alignement | Notes |
| ----- | ----- | ----- | ----- |
| [sym:TyRo98_TyIn170 typer](https://ontome.net/ns/symogih/TyRo98_TyIn170) | [sym:GenAbOb](https://ontome.net/ns/symogih/GenAbOb) |   |   |
| [sym:TyRo138_TyIn170 occasionner](https://ontome.net/ns/symogih/TyRo138_TyIn170) | [sym:Info](https://ontome.net/ns/symogih/Info) |   |   |
| [sym:TyRo210_TyIn170 est détruit](https://ontome.net/ns/symogih/TyRo210_TyIn170) | [sym:MaOb](https://ontome.net/ns/symogih/MaOb) |   |   |
| [sym:TyRo211_TyIn170 réalise](https://ontome.net/ns/symogih/TyRo211_TyIn170) | [sym:Actor](https://ontome.net/ns/symogih/Actor) |   |   |

### Commentaires

**Comment by valamercery** [comment]
Ce TyIn n'a aucune instance dans la BHP.
